services:
  - type: web
    name: my-web-service
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: pr-preview-service
    pullRequestPreviewsEnabled: true
    buildCommand: npm install
    startCommand: npm start
